# this file is meant for Docker Swarm stacks only
# trying it in compose will fail because of multiple replicas trying to bind to the same port
# Swarm currently does not support Compose Spec, so we'll pin to the older version 3.9

version: "3.9"

services:
  redis:
    image: redis:alpine
    networks:
      - frontend
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 8080:80
    networks:
      - frontend
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.http.routers.vote.rule=Host(`votacao.cognicode.tech`)"
        - "traefik.http.routers.vote.entrypoints=websecure"
        - "traefik.http.routers.vote.priority=1"
        - "traefik.http.routers.vote.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.vote.service=vote"

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 8081:80
    networks:
      - backend
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.http.routers.result.rule=Host(`resultado.cognicode.tech`)"
        - "traefik.http.routers.result.entrypoints=websecure"
        - "traefik.http.routers.result.priority=1"
        - "traefik.http.routers.result.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.result.service=result"

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2

networks:
  frontend:
  backend:

volumes:
  db-data:
